services:
  kunturtatto:
    container_name: kunturtatto
    image: kunturtatto:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://kunturtatto_db:3306/kunturtatto
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=012890
    depends_on:
      kunturtatto_db:
        condition: service_healthy  # Espera a que MySQL esté listo

  kunturtatto_db:
    container_name: kunturtatto_db
    image: mysql:8.0
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: 012890
      MYSQL_DATABASE: kunturtatto
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s  # Da más tiempo para iniciar

volumes:
  db_data:
